### YamlMime:ManagedReference
items:
- uid: UltraForce.Library.NetStandard.Security
  commentId: N:UltraForce.Library.NetStandard.Security
  id: UltraForce.Library.NetStandard.Security
  children:
  - UltraForce.Library.NetStandard.Security.UFCryptoHelper
  langs:
  - csharp
  - vb
  name: UltraForce.Library.NetStandard.Security
  nameWithType: UltraForce.Library.NetStandard.Security
  fullName: UltraForce.Library.NetStandard.Security
  type: Namespace
  assemblies:
  - UltraForce.Library.NetStandard
references:
- uid: UltraForce.Library.NetStandard.Security.UFCryptoHelper
  commentId: T:UltraForce.Library.NetStandard.Security.UFCryptoHelper
  href: UltraForce.Library.NetStandard.Security.UFCryptoHelper.html
  name: UFCryptoHelper
  nameWithType: UFCryptoHelper
  fullName: UltraForce.Library.NetStandard.Security.UFCryptoHelper
